// This file was generated by iSukces.Templates ver 1.26.104.9
// Get the latest version from https://raw.githubusercontent.com/isukces/iSukces.Templates/main/Code/iSukces.Templates/PrimitiveObsession.ttinclude

using System.Globalization;

namespace iSukces.Llm.Common;

[JsonConverter(typeof(ToolResultValueJsonConverter))]
public readonly partial struct ToolResultValue: IComparable, IComparable<string>, IComparable<ToolResultValue>, IEquatable<string>, IEquatable<ToolResultValue>
{
    public ToolResultValue(string? value) => _value = value?.Trim();

    public override bool Equals(object? obj) => obj is ToolResultValue x && Equals(x);

    public bool Equals(ToolResultValue other) => Comparer.Equals(Value, other.Value);

    public override int GetHashCode() => Comparer.GetHashCode(Value);

    public bool Equals(string? other) => Comparer.Equals(Value, other ?? string.Empty);

    public int CompareTo(ToolResultValue other) => Comparer.Compare(Value, other.Value);

    public int CompareTo(object? obj)
    {
        if (obj is null) return 1;
        return obj is ToolResultValue other
            ? CompareTo(other)
            : throw new ArgumentException($"Object must be of type {nameof(ToolResultValue)}");
    }

    public int CompareTo(string? other) => Comparer.Compare(Value, other ?? string.Empty);

    public override string ToString() => Value;

    public static implicit operator ToolResultValue(string? value) => new ToolResultValue(value);

    public static explicit operator string(ToolResultValue value) => value.Value;

    public static bool operator ==(ToolResultValue left, ToolResultValue right) => left.Equals(right);

    public static bool operator !=(ToolResultValue left, ToolResultValue right) => !left.Equals(right);

    private readonly string? _value;

    public string Value => _value ?? string.Empty;

    public static ToolResultValue Empty { get; } = new ToolResultValue(null);

    public bool IsEmpty => string.IsNullOrEmpty(_value);

    public static StringComparer Comparer => StringComparer.Ordinal;

    public static implicit operator ToolResultValue(int value)
        => new ToolResultValue(value.ToString(CultureInfo.InvariantCulture));

    public static implicit operator ToolResultValue(long value)
        => new ToolResultValue(value.ToString(CultureInfo.InvariantCulture));

    public static implicit operator ToolResultValue(decimal value)
        => new ToolResultValue(value.ToString(CultureInfo.InvariantCulture));

    public static implicit operator ToolResultValue(double value)
        => new ToolResultValue(value.ToString(CultureInfo.InvariantCulture));

    public static implicit operator ToolResultValue(float value)
        => new ToolResultValue(value.ToString(CultureInfo.InvariantCulture));

}

public sealed class ToolResultValueJsonConverter : JsonConverter
{
    public override bool CanConvert(Type objectType) => objectType == typeof(ToolResultValue);

    public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
    {
        return reader.Value switch
        {
            string stringValue => new ToolResultValue(stringValue),
            null => ToolResultValue.Empty,
            _ => throw new NotImplementedException()
        };
    }

    public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
    {
        if (value is null)
            throw new NullReferenceException("value is null");
        writer.WriteValue(((ToolResultValue)value).Value);
    }

}

